apiVersion: v1
kind: Pod
metadata:
  name: statsd
  labels:
    app: statsd
spec:
  containers:
  - name: statsd
    image: prom/statsd-exporter
    ports:
    - containerPort: 9102
      protocol: TCP
    - containerPort: 9125
      protocol: TCP
    - containerPort: 9125
      protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: statsd
spec:
  ports:
  - port: 9102
    protocol: TCP
    targetPort: 9102
    name: asd
  - port: 9125
    protocol: TCP
    name: bsd
    targetPort: 9125
  - port: 9125
    protocol: UDP
    name: csd
    targetPort: 9125
  selector:
    app: statsd